services:
  - type: web
    name: taishunhe-backend
    plan: starter
    env: docker
    region: singapore

    dockerfilePath: ./Dockerfile

    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: taishunhe-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: taishunhe-redis
          type: redis
          property: connectionString
  - name: taishunhe-redis
    type: redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: ["0.0.0.0/0"]

databases:
  - name: taishunhe-db
    plan: starter
    region: singapore